version: '2.1'
services:
#  rabbitmq:
#    ports:
#      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-postgres:
    build: postgres
    ports:
      - 25000:5432

  account-service:
    build: account-service
    ports:
      - 6000:6000

  account-postgres:
    build: postgres
    ports:
      - 26000:5432
#
#  statistics-service:
#    build: statistics-service
#    ports:
#      - 7000:7000
#
#  statistics-mongodb:
#    build: mongodb
#    ports:
#      - 27000:27017
#
#  notification-service:
#    build: notification-service
#    ports:
#      - 8000:8000
#
#  notification-mongodb:
#    build: mongodb
#    ports:
#      - 28000:27017

#  monitoring:
#    build: monitoring
#
#  turbine-stream-service:
#    build: turbine-stream-service