security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

#spring:
#  data:
#    mongodb:
#      host: account-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
#      port: 27017

spring:
  datasource:
    url:    jdbc:postgresql://account-postgres:5432/database
    username: user
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true