#spring:
#  data:
#    mongodb:
#      host: auth-mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
#      port: 27017
#
#server:
#  servlet:
#    context-path: /uaa
#  port: 5000



spring:
  datasource:
    url:    jdbc:postgresql://auth-postgres:5432/database
    username: user
    password: ${POSTGRES_PASSWORD}

  # Spring Data JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  servlet:
    context-path: /uaa
  port: 5000
